### ISSUE TITLE
Adding methods to another package's R6 class: how to document?

### ISSUE THREAD

**Issue by Hong-Revo** [klutometis/roxygen#807] opened 2018-10-19 09:34 UTC
R6 has a nifty feature where you can add new members to an existing class via `set()`. You can even do this to a class exported by a different package, which is very useful indeed.

For example, in package A:
```r
#' @export
myclass <- R6::R6Class("myclass",
    public=list(
        f=function(x) { ... }
))
```
And in package B:
```r
# modifying objects exported by another package must be done at runtime
.onLoad <- function(libname, pkgname)
{
    A::myclass$set("public", "g", overwrite=TRUE,
        function(y) { ... }
}
```
Now you can do something like
```r
library(A)
library(B)
obj <- A::myclass$new(...)
obj$g(y=42)  # method defined by package B
```
How should we document the new method added by B?

**Comment by hadley** [comment] 2019-07-20 15:07
Effectively a duplicate of #388, since we don't have any way to document any R6 class.

**Closed by hadley** 2019-07-20 15:07 UTC
