### ISSUE TITLE
definitions of overloaded methods in a subclass are ignored

### ISSUE THREAD

**Issue by pbiecek** [klutometis/roxygen#366] opened 2015-08-04 21:07 UTC
See this example:
http://stackoverflow.com/questions/25653505/roxygen2-ignores-subclass-constructor-docstring

The documentation for the 'initialize' method for the subclass 'YourClass' is replaced by documentation from masterclass 'Myclass'.

Possible because of line 9 in 
https://github.com/klutometis/roxygen/blob/master/R/rc.R

The rc_methods() returns only methods that are not defined in the masterclass.

**Comment by hadley** [comment] 2015-10-05 13:42
Can you please provide a minimal reprex inline?

**Comment by pbiecek** [comment] 2015-10-05 18:55
The example is on SO, here I copy it.

The problem:
After document() and install() I can query `?Yourclass` but as result I will get list of functions from `Myclass` (here only initialize).

```{r}
#' myclass 
#' @field fa A number
#' @field fb A number
#' @field filename A filename
#' @field data A data frame
Myclass = setRefClass("Myclass",
                      fields = list(
                          fa = "numeric",
                          fb = "numeric",
                          data = "data.frame"
                      )
)


Myclass$methods(
    initialize = function(fa = NULL, fb = NULL, filename = NULL) {
        "constructor of myclass"
        if(!is.null(fa) && !is.null(fb) && !is.null(filename)) {
            message("Initializing object in class...")
            .self$fa = fa
            .self$fb = fb
            .self$data = read.table(.self$filename, header=TRUE)
        }
    }
)

#' A subclass of myclass
Yourclass = setRefClass("Yourclass", fields = list(msg = "character"), contains = "Myclass")

Yourclass$methods(
    initialize = function(..., msg = NULL) {
        "constructor of Yourclass, just added a message."
        callSuper(...)
        if(!is.null(msg)) {
            message(msg)
        }
    }
)
```

**Comment by hadley** [comment] 2015-10-05 18:58
Duplicate of #278

**Closed by hadley** 2015-10-05 18:58 UTC
