### ISSUE TITLE
Improve wrapping for usage sections

### ISSUE THREAD

**Issue by hughjonesd** [klutometis/roxygen#806] opened 2018-10-18 11:16 UTC
When functions have many arguments, the default wrapping of their \usage section is hard to read. For example, `readr::read_delim` looks like:
```
read_delim(file, delim, quote = "\"", escape_backslash = FALSE,
  escape_double = TRUE, col_names = TRUE, col_types = NULL,
  locale = default_locale(), na = c("", "NA"), quoted_na = TRUE,
  comment = "", trim_ws = FALSE, skip = 0, n_max = Inf,
  guess_max = min(1000, n_max), progress = show_progress())
```

This saves vertical space, but makes it hard to spot argument names and to distinguish them from default values. It would sometimes be nicer to have one argument per row. For example, `lattice::xyplot` does

```
xyplot(x,
       data,
       allow.multiple = is.null(groups) || outer,
       outer = !is.null(groups),
       auto.key = FALSE,
       aspect = "fill",
       panel = lattice.getOption("panel.xyplot"),
       prepanel = NULL,
       scales = list(),
       strip = TRUE,
       groups = NULL,
       xlab,
       xlim,
       ylab,
       ylim,
       drop.unused.levels = lattice.getOption("drop.unused.levels"),
       ...,
       lattice.options = NULL,
       default.scales,
       default.prepanel = lattice.getOption("prepanel.default.xyplot"),
       subscripts = !is.null(groups),
       subset = TRUE)
```

The most flexible solution would be to have the usage laid out just as it is in the original code. At the moment, roxygen reformats usage sections.

**Comment by hadley** [comment] 2019-07-20 15:06
Duplicate of #820

**Closed by hadley** 2019-07-20 15:06 UTC
