### ISSUE TITLE
"Depends: R (>= 3.0.2)" in DESCRIPTION is misleading

### ISSUE THREAD

**Issue by mvkorpel** [klutometis/roxygen#582] opened 2017-02-07 13:38 UTC
This is a minor wishlist item asking for "Depends: R (>= 3.2.0)" to be used instead, as roxygen2 imports desc, the current version (1.1.0) and all historic CRAN versions of which depend on R >= 3.2.0. I have tested that roxygen2 6.0.1 can be installed on R 3.2.0.

**Comment by hadley** [comment] 2017-02-07 14:33
I'd rather push desc back to R 3.0.2 compatibility (or at least 3.1.0). @gaborcsardi do you think that would be a lot of work?

**Comment by gaborcsardi** [comment] 2017-02-07 14:34
BTH I forgot why 3.2.0 is needed, but will check in a minute.

**Comment by gaborcsardi** [comment] 2017-02-07 15:17
All right, I am still not exactly sure. `Authors@R` is parsed differently from 3.2.0, that's why I added it. To avoid these errors: https://travis-ci.org/r-pkgs/desc/builds/91095283

I'll get an R 3.0.2 install....

**Comment by gaborcsardi** [comment] 2017-02-07 16:35
OK, I can probably do R 3.1.0. R 3.0.2 is a pain even just to install, on macOS or Linux....
I'll try to fix `desc` soon. Looks like only `utils:::format.person(..., style = "R")` is missing from R 3.1.0, at least for the test cases.

**Comment by gaborcsardi** [comment] 2017-02-08 01:47
OK, `desc` needs only R 3.1.0 now.

It might even work on R 3.0.2, actually, but it is too much work to check that.

**Comment by mvkorpel** [comment] 2017-02-08 12:04
I tried `R CMD check` on `desc` with R 3.0.2, after manipulating the `Depends` field to only require `R >= 3.0.2`. For doing a complete `R CMD check`, the suggested package `covr` is not available, not even as a historic version. Setting `_R_CHECK_FORCE_SUGGESTS_` to `0` allows the check to proceed anyway. After that, the problem is that only `testthat` 0.9 or earlier works on R 3.0.2. In `testthat` 0.9, some functions used by `desc` (`expect_silent`, `expect_lt`, `expect_gt`) are not available, and `with_mock` does not work (on R 3.0.2). After that I gave up.

**Comment by hadley** [comment] 2017-02-08 13:13
@gaborcsardi can you give me a version number I can depend on for 3.1 support? I'll also add the check to travis

**Comment by gaborcsardi** [comment] 2017-02-08 13:30
@hadley Yes, `desc (>= 1.1.0.9000)`.

The last CRAN release was 2017-01-27, so I'll wait a bit and then release it.

**Comment by gaborcsardi** [comment] 2017-02-08 13:38
Btw. R Travis does not work with R 3.1.3 it seems: 
https://travis-ci.org/r-pkgs/desc/jobs/199606212#L1075

**Comment by jimhester** [comment] 2017-02-08 13:53
This is caused by a bug in CRAN devtools, it is fixed in devel. https://github.com/hadley/devtools/pull/1250

`before_install: source("https://install-github.me/hadley/devtools")` is probably the easiest way to use devel devtools. Thanks @gaborcsardi!

**Comment by gaborcsardi** [comment] 2017-02-08 14:02
WAit, don't you have to write `R -q -e "source(...)"`?

**Comment by jimhester** [comment] 2017-02-08 14:18
Oh you do sorry, `Rscript -e 'source()'`

**Comment by jimhester** [comment] 2017-02-08 15:09
Alternatively it could be `curl -sSL 'https://install-github.me/hadley/devtools' | Rscript -`, but the all R version is probably nicer I think.

**Comment by gaborcsardi** [comment] 2017-02-08 15:12
@jimhester Not so easy: 
```
https:// URLs are not supported
```
https://travis-ci.org/r-pkgs/desc/jobs/199636873#L514

Not sure how I could work around this....

**Comment by gaborcsardi** [comment] 2017-02-08 15:12
@jimhester Oh, yeah, your alternative method is good for this! :)

**Comment by gaborcsardi** [comment] 2017-02-08 15:13
Except that it is not, because the GitHub URL is HTTPS as well....

**Comment by jimhester** [comment] 2017-02-08 15:34
Hmm you can do

```yaml
r_github_packages:
  - hadley/devtools
```

It will install devtools twice, which is what I was trying avoid, but it should work (hopefully)...

**Comment by gaborcsardi** [comment] 2017-02-08 15:50
@jimhester Tried, no luck. :( I am giving this up for now... I could maybe download and install `curl` manually, or something like this...

https://travis-ci.org/r-pkgs/desc/jobs/199649309#L1074-L1085

```
Installing R packages from GitHub: hadley/devtools
1.95s$ Rscript -e 'devtools::install_github(c("hadley/devtools"), build_vignettes = FALSE)'
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Downloading GitHub repo hadley/devtools@master
from URL https://api.github.com/repos/hadley/devtools/zipball/master
Installing devtools
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Using bundled GitHub PAT. Please add your own PAT to the env var `GITHUB_PAT`
Error in if (capabilities("libcurl")) { : argument is of length zero
Calls: <Anonymous> ... download_method_secure -> download_method -> auto_download_method
```

**Comment by hadley** [comment] 2017-02-08 16:28
Let's not worry about this for now - once devtools is working again, we'll make sure to do a systematic pass to make sure that everything works on 3.1

**Closed** 2017-08-16 15:51 UTC
