### ISSUE TITLE
Warning: bad markup (extra space?) - automatic cut of line when @inheritParams

### ISSUE THREAD

**Issue by DominiqueMakowski** [klutometis/roxygen#866] opened 2019-05-20 09:36 UTC
I have a package in which there is this [argument description](
https://github.com/easystats/bayestestR/blob/de682e173484b2b11db3acbd3c2269f2144231dc/R/describe_posterior.R#L8):

`#' @param rope_range \href{https://easystats.github.io/bayestestR/rope}{ROPE's} lower and higher bounds. Should be a list of two values (e.g., \code{c(-0.1, 0.1)}) or \code{"default"}. If \code{"default"}, the bounds are set to \code{x +- 0.1*SD(response)}.`

The package documentation builds without problems. 

However, in another package, I [inherit this parameter from the first package](https://github.com/easystats/parameters/blob/df9bf9557f6d9ca47f437bfaf2b4c24573046b22/R/model_parameters.bayesian.R#L69). Then, upon compilation of this second package, I got the error:

`Warning: bad markup (extra space?)`

And when I look at the created documentation, it seems like roxygen cut the first part of the line, leaving only:

`c(-0.1, 0.1)) or "default". If "default", the bounds are set to x +- 0.1*SD(response).`

How can I address that? Thank you!

I have `roxygen2_6.1.1`.

**Comment by strengejacke** [comment] 2019-05-28 07:47
This error seems to occur when the _original_ roxygen-part contains `\href{}`-tags in the docs. These cause troubles when inheriting params from other packages.

**Comment by jennybc** [comment] 2019-06-18 09:05
I am seeing this error also. My hyperlink is gaining an extra set of `{}` in the inherited form, that it does not have in the source package.

Roxygen comments for this parameter:

``` r
#' @param path JSON obtained from [Google Developers
#'   Console](https://console.developers.google.com), containing a client id
#'   (aka key) and secret, in one of the forms supported for the `txt` argument
#'   of [jsonlite::fromJSON()] (typically, a file path or JSON string).
```

which gives rise to this Rd in the source package:

``` r
\item{path}{JSON obtained from \href{https://console.developers.google.com}{Google Developers Console}, containing a client id
(aka key) and secret, in one of the forms supported for the \code{txt} argument
of \code{\link[jsonlite:fromJSON]{jsonlite::fromJSON()}} (typically, a file path or JSON string).}
```

and gives rise to this Rd in a child package that uses `@inheritParams`:

``` r
\item{path}{JSON obtained from \href{{https://console.developers.google.com}{Google Developers Console}}, containing a client id
(aka key) and secret, in one of the forms supported for the \code{txt} argument
of \code{\link[jsonlite:fromJSON]{jsonlite::fromJSON()}} (typically, a file path or JSON string).}
```

**Comment by jennybc** [comment] 2019-06-18 09:06
What @strengejacke and I are talking about appears to be #778

**Comment by hadley** [comment] 2019-07-21 12:35
Duplicate of #778

**Closed by hadley** 2019-07-21 12:35 UTC
