### ISSUE TITLE
Recognize and format roxygen2 tags in Reference Class Method docstrings 

### ISSUE THREAD

**Issue by lukedomanski** [klutometis/roxygen#196] opened 2014-02-16 10:53 UTC
It would be highly desirable for general function/method tags to be recognized within Reference Class method docstrings, then formatted nicely within the classes' documentation page. This would bring roxygen inline with both Doxygen, and JavaDocs, which both support the use of tags within class method documentation.

As discussed in #168, roxygen tags within docstrings are currently regarded and formatted as plain text verbatim.

See https://gist.github.com/lukedomanski/8946577 for an example of the current roxygen2 .rd output (+ its Rd2HTML conversion) for Reference Class methods containing tags, and a modified version of the .rd output file (+ Rd2HTML conversion) showing one way that tags might/should be formatted in the output.

**Comment by DealerUplift-DavidJohnston** [comment] 2015-06-15 22:32
In addition to getting some better formatting it would be nice to be able to either include a "collate" dynamic where one could explicitly name methods in the order they should appear in the final documentation or preserve the lexical order.  Alphabetical sorting is an OK default but if methods act on a similar subset of functional "set/get/reset" <functionality> having the three methods separated is not ideal.

As to having separate .Rd files that seems, at first blush, less than ideal as well.  If I'm viewing the documentation for the reference class definition I'd rather see all fields and methods listed thereunder.  A summary/detail setup would not be out of the question though.  If tags can be recognized the user can display appropriate content for each; and if a "returns" tag is specified it would ideally be incorporated into the summary section as part of the method signature.

Related to the first paragraph - the order in the summary and the order in the detail could be different...

Also, "currently" (maybe not "most recent") I'm seeing the spacing of the docstring content, when adding a manual newline, to be double-spaced just like in between method names.  Having the docstring content be single spaced (maybe 1.5, include between the method signature and the first line) with the last line of the docstring and the next method double-spaced would maybe be more visually appealing.

```
      "Set new lower and upper index bounds.\n
       @param integer representing lower bound\n
       @param integer representing upper bound\n
       @returns .self"
```
yields: setBounds(name integer, name integer) : .self
```
      "Get the lower and upper index values that restrict
       the rows that are plotted or analyzed.\n
       @returns vector(numeric) an integer vector of length 2 representing the
       lower and upper bounds."
```
yields: getBounds() : vector(numeric)

**Comment by hadley** [comment] 2015-10-07 15:17
Now duplicate of #388

**Closed by hadley** 2015-10-07 15:17 UTC
