### ISSUE TITLE
Wish:Enhanced visualization for functions documenting 

### ISSUE THREAD

**Issue by huangwb8** [klutometis/roxygen#827] opened 2018-11-22 03:19 UTC
I am new of roxygen2 and I have a wish as following.

For example,the Usage of  WGCNA::moduleEigengenes function looks like this:
![image](https://user-images.githubusercontent.com/35643122/48879397-77cf5d00-ee46-11e8-929f-72dc4e00d7bf.png)
,which is well-bedded.I found the authors of WGCNA package directly edit the .Rd file instead of using roxygen2. 

If roxygen2 is used(@export for the function),it always looks like this:
![image](https://user-images.githubusercontent.com/35643122/48879522-18258180-ee47-11e8-9869-a153834191d6.png)
,which is less-bedded.

If the number of parameters of a funtion is large,the first style,I think, would be more friendly for my readers(or me).But I had no idea how to make similar visualization by roxgen2.

Do you have any advice?Thank you very much!

**Comment by hadley** [comment] 2019-07-20 15:18
Duplicate of #820

**Closed by hadley** 2019-07-20 15:18 UTC
