### ISSUE TITLE
Bug in @export for as.vector?

### ISSUE THREAD

**Issue by MansMeg** [klutometis/roxygen#483] opened 2016-06-12 12:25 UTC
Thanks for a great package!

Im having problem getting this roxygen functionality to work with @export (@S3method works fine).

```
#' Convert json stat object to numeric vector
#'
#' @details
#' This converts a json stat object to a vector. It essentially just
#' returns the value slot of a json stat object.
#'
#' @seealso \code{\link{as.vector}}
#'
#' @param x
#' a \code{jsonstat_dataset} object
#' @param mode
#' character string naming an atomic mode or "\code{list}" or
#' "\code{expression}" or (except for \code{vector}) "\code{any}".
#'
#' @export
as.vector.jsonstat_dataset <- function(x, mode = "any"){
    as.vector(x$value, mode)
}
```

**Comment by hadley** [comment] 2016-08-29 15:43
Duplicate of #488

**Closed by hadley** 2016-08-29 15:43 UTC
