### ISSUE TITLE
Error with setClassUnion.

### ISSUE THREAD

**Issue by jcrodriguez1989** [klutometis/roxygen#585] opened 2017-02-08 15:30 UTC
I am having an error with setClassUnion since roxygen2 got updated.
It is quite a simple code:
```
## ExprData-class.R
#'ExprData S4 class implementation in R
#' 
#'This S4 class contains the expression data, it can be a MAList or DGEList.
#'Important: Rownames are going to be used as gene identifiers, make sure that 
#'this IDs are the same used in your gene sets.
#'
#'@docType methods
#'@name ExprData-class
#'@rdname ExprData-class
#'
#'@importClassesFrom edgeR DGEList
#'@importClassesFrom limma MAList
#'@export ExprData
setClassUnion("ExprData", c("MAList", "DGEList"));
```

Error:
```
> system("R CMD REMOVE MIGSA");
> library("devtools");
> library("roxygen2");
> require("edgeR");
Loading required package: edgeR
Loading required package: limma
> require("limma");
> package.skeleton('MIGSA', code_files=c(
+     'ExprData-class.R'
+ ), force=TRUE)
Creating directories ...
Creating DESCRIPTION ...
Creating NAMESPACE ...
Creating Read-and-delete-me ...
Copying code files ...
Making help files ...
Done.
Further steps are described in './MIGSA/Read-and-delete-me'.
> roxygenise(package.dir="MIGSA");
First time using roxygen2. Upgrading automatically...
Updating roxygen version in /home/jcrodriguez/Dropbox/R/MIGSA_creating/MIGSA/DESCRIPTION
Loading required package: roxygen_devtest
Error in .requirePackage(package) : 
  unable to find required package ‘roxygen_devtest’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘roxygen_devtest’
Loading required package: roxygen_devtest
Error in .requirePackage(package) : 
  unable to find required package ‘roxygen_devtest’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘roxygen_devtest’
Error in setClassUnion("ExprData", c("MAList", "DGEList")) : 
  unable to create union class:  could not set members "MAList", "DGEList"
```

I cant find any workout, please help.
Rodriguez, Juan C.

**Comment by jcrodriguez1989** [comment] 2017-02-08 15:59
Well, I found a workaround, going back to older roxygen version ha!
`git checkout 4d3b35c`

**Comment by pan0ramic** [comment] 2017-02-10 01:00
I get these same errors. FWIW when I swapped `roxygenizse()` for `devtools::document()` I stopped getting the errors.

**Comment by jpritikin** [comment] 2017-02-16 01:44
This affects `OpenMx` too. I was able to find another solution to avoid `setOldClass` #568, but I don't think I can avoid the `setClassUnion`.

**Comment by jpritikin** [comment] 2017-02-17 14:37
Due to the large amount of C++ code involved in building `OpenMx`, the `devtools` work-around is about 100 times slower than `roxgenize` was.

**Comment by hadley** [comment] 2017-08-16 15:00
Duplicate of #568

**Closed by hadley** 2017-08-16 15:00 UTC
