### ISSUE TITLE
no-build option for roxygenise?

### ISSUE THREAD

**Issue by spennihana** [klutometis/roxygen#776] opened 2018-08-09 21:05 UTC
How do I get back the old behavior of roxygen that works on source files only without package building steps. Upgrading to the most recent of roxygen2 now attempts to do a package build which is undesirable.

Thanks

**Comment by eddelbuettel** [comment] 2018-08-15 22:17
I asked for the same in #771 and have as soundly ignored as you.  

I resorted to keeping 6.0.1 in a local directory and use that instead.

**Comment by hadley** [comment] 2018-08-21 11:53
Duplicate of #771

**Closed by hadley** 2018-08-21 11:53 UTC
