### ISSUE TITLE
Looks for but can't find roxygen_devtest on R 3.3.3 

### ISSUE THREAD

**Issue by JoFAM** [klutometis/roxygen#618] opened 2017-04-03 15:52 UTC
RStudio version 1.0.136
Roxygen2 version 6.0.1
R version 3.3.3

If I try to run the documentation for my package, I get following error:

Error in .requirePackage(package) :
  unable to find required package 'roxygen_devtest'

If I select R 3.3.1 manually, restart RStudio and try again, it works. Moving back to R 3.3.3 gives the same error again. If I try it in the R terminal of R 3.3.3 using 

roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))

I get the same error.

**Comment by JoFAM** [comment] 2017-04-04 08:48
I've tried this on a Windows 7 computer at work and couldn't reproduce. Same package, same git repo, same installation. So apparently the culprit lies somewhere else. I'm going to try again tonight to investigate further.

**Comment by JoFAM** [comment] 2017-04-04 18:40
Update: on the Windows 7 computer, devtools was installed as well. Therefor RStudio uses document::devtools() instead of roxygen2::roxygenize(). If I install devtools on the Windows 10 computer, RStudio works fine.

Using roxygen2::roxygenize(...) keeps failing on R 3.3.3 but works on older versions.

**Comment by jeroen** [comment] 2017-04-07 10:16
+1 same problem.

**Comment by bwlewis** [comment] 2017-04-10 00:32
+1 same problem on Debian Linux with R-devel
```{r}
roxygen2::roxygenise()
## ...
## Loading required package: roxygen_devtest
## Error in .requirePackage(package) : 
##   unable to find required package ‘roxygen_devtest’
## In addition: Warning message:
## In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
##   there is no package called ‘roxygen_devtest’

R.version["version.string"]
##                _                                       
## version.string R version 3.4.0 beta (2017-04-08 r72499)
```

**Comment by dankelley** [comment] 2017-04-22 23:07
Ditto macos sierra.

**Comment by dankelley** [comment] 2017-04-22 23:16
Oh, skip that last comment I made re macos sierra. This was because I had installed R 3.4.0 and had installed `roxygen2` without also installing `devtools`. With the latter in place, there's no problem for me. Sorry for the noise.

**Comment by JoFAM** [comment] 2017-05-22 09:48
@dankelley unless roxygen indicates that it depends on devtools, this is a bug. Devtools is mentioned in "Suggests", but the main function of the package should work without having the packages in Suggests installed. So either they move devtools to Depends, or they fix that bug.

**Comment by hadley** [comment] 2017-08-16 16:04
Duplicate of #595

**Closed by hadley** 2017-08-16 16:04 UTC
